# Generated by Django 4.2.6 on 2023-10-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateField(),
        ),
    ]
